### ISSUE TITLE
Error installing to BXT_GP board

### ISSUE THREAD

**Issue by matthewrsj** [bryteise/ister#119]
Originally reported by @zyuan2x in https://github.com/clearcontainers/runtime/issues/869

The following error is encountered when installing Clear Linux to a BXT_GP board:

`fdisk: cannot open /dev/mmcblk0rpmb: Input/output error`

@bryteise I thought you resolved this issue in https://github.com/bryteise/ister/pull/118/commits/92305ebd92dab070e7c6dafc0acd56b6cafe7547

**Comment by zyuan2x** [comment]
Does "Add exception handling to get_disk_info #120" patch in the latest image clear-19780-installer.img.xz  ?

**Comment by matthewrsj** [comment]
There hasn't been a new release of ister yet. I'll do that today and the new version should be in this afternoon's build. I'm going to leave this issue open until we can be sure the issue is resolved.

**Comment by zyuan2x** [comment]
Install Clear Linux on BXT_GP:
Result: Installed successfully with the image clear-19810-installer.img.xz

**Comment by zyuan2x** [comment]
@matthewrsj  You can free to close this issue. Very thanks for your support.
