### ISSUE TITLE
Ister should use pytest

### ISSUE THREAD

**Issue by hunger** [bryteise/ister#134]
Ister should use pytest instead of writing is own test harness.

To do so will require a bit of refactoring (e.g. have a proper package instead of lumping everything into three files, so this involves a bit of work:-).

I would be willing to help with that, if you are willing to move into that direction.

**Comment by hunger** [comment]
I started playing with a ister package in https://github.com/hunger/ister :-)

**Comment by bryteise** [comment]
I would probably hold off on working on it. Ister is going to be replaced by another project that is much better built for the task, I am not sure exactly when the release is coming but it is quite far along.

**Comment by hunger** [comment]
/me sighs.

Any ETA? Can I clone the code from somewhere to take a look whether that will be a better match for what I want to do?
