### ISSUE TITLE
Consider installation as a CLI tool via pip

### ISSUE THREAD

**Issue by shrmrf** [bryteise/ister#144]
Hello @bryteise 

Is it a good idea to be able to install `ister` as a CLI utility via pip? (`pip install https://some-url`)

I can submit a PR for that but I expect a lot of filesystem refac.
Regards

**Comment by bryteise** [comment]
Aside from Clear moving to deprecate ister for clr-installer (though maybe not for awhile longer as a CLI utility for image creation) it isn't a bad idea. At this point though ister is a drop in python script that doesn't have anything it installs in lib nor does it really need any other files on the system so aside from the familiarity of using pip to get python programs it doesn't provide much in the way of convenience. The other thing is that ister requires swupd to function so you need to already be on a Clear system to use it and swupd already provides a way to install ister and all its many non python dependencies that pip wouldn't help bring in.

**Comment by shrmrf** [comment]
Alright. Makes a lot of sense...
