### ISSUE TITLE
An invalid bundle name is still added to an image

### ISSUE THREAD

**Issue by bktan8** [bryteise/ister#155]
Even though the warning message says an invalid bundle is being skipped, the bundle name still shows up when you do "swupd bundle-list" for the created image.

Example:
clear@clr-da50329d227d4062bb2170a8b8162bd2 ~/mixer $ sudo -E mixer build image
Password:
Reading configuration
Validating configuration
Creating virtual disk
Creating partitions
Mapping loop device
Creating file systems
Setting up mount points
Starting swupd. May take several minutes
Installing 4 bundles (and dependencies)...
.
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Verifying version 10
Warning: Bundle "BADBUNDLE" is invalid, skipping it...
Downloading packs...

STEPS TO REPRO:
1) Add an invalid bundle name to config json file.
2) Create an image
3) Boot up the image
4) swupd bundle-list and you can see the invalid bundle name

**Comment by bryteise** [comment]
Hrm if a user inserts an invalid bundle name into the template, they kind of get what they get. This is not a bug territory for me.

**Comment by bktan8** [comment]
Turns out this is acutally a swupd-client issue.  It's related to https://github.com/clearlinux/swupd-client/issues/608.
