### ISSUE TITLE
'No such file or directory' at end of mixer image build.

### ISSUE THREAD

**Issue by cedws** [bryteise/ister#161]
Towards the end of building an image with mixer, I get a small non-fatal error which I think might be the output of ister. The referenced path looks a bit weird.

```
$ sudo mixer build image
...
Inspected 8386 files
  8379 files were missing
    8379 of 8379 missing files were replaced
    0 of 8379 missing files were not replaced
Calling post-update helper scripts.
sh: /tmp/ister-latest-6uuayzoc///usr/bin/update-helper: No such file or directory
Fix successful
Cleaning up
Successful installation
```

Thanks.

**Comment by bryteise** [comment]
@c-edw That's actually from swupd-client, the path is fine though as that's the target location of the mounted drive. Just an optional update script that I'm guessing your mix didn't have.

**Comment by cedws** [comment]
It's very difficult to tell what tool is outputting what when it's all dumped to stdout. 

In this scenario, could it check for the existence of the `update-helper` script before attempting to delete it?

**Comment by bryteise** [comment]
In this case swupd-client is trying to run update-helper. swupd-client could check that it exists before it tries to execute it though I agree.

**Comment by cedws** [comment]
Alright, are you able to move this issue to swupd-client's repo? Or should I file another issue there?

**Comment by bryteise** [comment]
You'll need to open a new issue since this isn't under the same namespace.
